version: '3'

networks:
  backend:
    driver: bridge

services:
  php:
    container_name: php
    restart: always
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    ports:
      - "9501:9501"
    networks:
      - backend
