name: PHPUnit for whell

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  ci:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: phpize
          extensions: redis, pdo, pdo_mysql, bcmath
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Get Swoole Version
        shell: bash
        id: vars
        run: |
          swoole_version=$(response=$(curl -s -i https://github.com/swoole/swoole-src/releases/latest | grep 'location' | head -n 1) && echo ${response##*/v})
          echo "::set-output name=swoole_version::$swoole_version"
      - name: Setup Swoole
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libc-ares-dev libpq-dev
          wget https://github.com/swoole/swoole-src/archive/v${{steps.vars.outputs.swoole_version}}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-swoole-curl --enable-cares --enable-swoole-pgsql
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/8.1/cli/conf.d/swoole.ini"
          sudo sh -c "echo swoole.use_shortname='Off' >> /etc/php/8.1/cli/conf.d/swoole.ini"
          php --ri swoole
      - name: Setup Services
        run: |
          docker run --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d mysql:5.7 --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
          docker run --name redis -p 6379:6379 -d redis
          docker run -d --restart=always --name rabbitmq -p 4369:4369 -p 5672:5672 -p 15672:15672 -p 25672:25672 rabbitmq:management-alpine
      - name: Run Test Cases
        run: |
          composer install
          composer test
